### PR TITLE
VGNWB-92: Added column for publication date in text\text-list

### PR DESCRIPTION
**Pull request by harshaneelhg**

### CODE REVIEW

**Comment by erickpeirson** [comment]
image

Looks awfully smooshed; any way to move it left of count, and give it more space?

**Comment by erhkamal** [comment]
Can we specify the width with CSS? Currently it adjusts based on the length of the title. 
EDIT:Folds to the next line even if moved to left of count.

**Comment by erickpeirson** [comment]
@erhkamal319 Did you try the bootstrap column width classes?

**Comment by erhkamal** [comment]
Yeah, we are on it.

**Comment by erickpeirson** [comment]
Much better; thanks!

**Pull request merged**
