### PR TITLE
[VGNWB-351] Citesphere Integration

### PR DESCRIPTION
**Pull request by nowke**
* Add Citesphere API class
* Refactor repository URLs - separate Amphora and Citesphere related endpoints

Related Frontend PR - https://github.com/diging/vogon-web-client/pull/55

### CODE REVIEW

**Comment by tjquinn1** [comment]
fix conflicts

**Comment by tjquinn1** [comment]
Fix failed build

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
resolve conflicts

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
What setup config is needed for this? I see there is citeshpere properties in the settings file. Please add whats needed to the vogon setup confluence. Once that is done I will merge it.

**Comment by nowke** [comment]
> What setup config is needed for this? I see there is citeshpere properties in the settings file. Please add whats needed to the vogon setup confluence. Once that is done I will merge it.

Updated in https://diging.atlassian.net/wiki/spaces/VGNWB/pages/2086273044/Vogon+Initial+Setup#Citesphere-Configuration

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Pull request merged**
