### PR TITLE
[VGNWB-102] Added all the github links to all profiles on the 'About' page

### PR DESCRIPTION
**Pull request by jasdeepbhalla**

### CODE REVIEW

**Comment by erickpeirson** [comment]
Great start! Can you add a little more padding below the links? They are right up against the image below

image

**Comment by jasdeepbhalla** [comment]
Added padding to image divs

**Comment by erickpeirson** [comment]
@jasdeepbhalla Looks good, thanks! Can you resolve the merge conflicts, and then we'll merge this.

**Comment by jasdeepbhalla** [comment]
Resolved the conflicts!

**Pull request merged**
