### PR TITLE
[VGNWB-340] Add predicate to appellations

### PR DESCRIPTION
**Pull request by nowke**
Related frontend PR - https://github.com/diging/vogon-web-client/pull/46

### CODE REVIEW

**Comment by tjquinn1** [comment]
see front end

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
See FE

**Comment by nowke** [comment]
Resolved FE issues

**Comment by nowke** [comment]
Closing this PR - will implement "Delete appellation" feature with this - https://diging.atlassian.net/browse/VGNWB-253

**Comment by nowke** [comment]
Added Delete appellation functionality

**Comment by tjquinn1** [comment]
fix code factor issues

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Pull request merged**
