### PR TITLE
[VGNWB-329] Project collaboration

### PR DESCRIPTION
**Pull request by nowke**
- Participants support for projects
- Notification integration

Related FE - https://github.com/diging/vogon-web-client/pull/60

### CODE REVIEW

**Comment by tjquinn1** [comment]
please fix the failing checks

**Comment by tjquinn1** [comment]
notifications needs to be added to apps in settings.py

```
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'notifications'
```

**Comment by nowke** [comment]
It is already part of `settings.py` - https://github.com/diging/vogon-web/blob/story/VGNWB-329/vogon/settings.py#L44

You may need to install the new package `django-notifications-hq==1.6.0` and `django-model-utils==4.0.0` and try again. 

These changes are added to `Pipfile` and `requirements.txt` as part of this Pull request.

**Comment by tjquinn1** [comment]
front end branch is still closed

**Comment by tjquinn1** [comment]
resolve conflicts on BE.

**Comment by tjquinn1** [comment]
see front end

**Comment by tjquinn1** [comment]
resolve conflicts. The front end also has conflicts that haven't been resolved.

**Comment by tjquinn1** [comment]
fix build issues

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
See FE

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Comment by tjquinn1** [comment]
Fix FE

**Comment by tjquinn1** [comment]
Make it so, Jenkins.

**Pull request merged**
